// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDicAsaF-Tn50J4ldiCNkkdi7uD0SN11Pk',
    appId: '1:330270178010:web:d5c585797d25061f5003e3',
    messagingSenderId: '330270178010',
    projectId: 'xorbx-app',
    authDomain: 'xorbx-app.firebaseapp.com',
    storageBucket: 'xorbx-app.firebasestorage.app',
    measurementId: 'G-X9D4QKV07H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCBblaBy8b9IWkc3B_qXe5kQmGhMrFwHiM',
    appId: '1:330270178010:android:08d7cb19894903a95003e3',
    messagingSenderId: '330270178010',
    projectId: 'xorbx-app',
    storageBucket: 'xorbx-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA39lS3A3sxMFej20wDfEzA6WXUokiul9E',
    appId: '1:330270178010:ios:37e4d6ddbb7edc675003e3',
    messagingSenderId: '330270178010',
    projectId: 'xorbx-app',
    storageBucket: 'xorbx-app.firebasestorage.app',
    iosBundleId: 'com.example.xorbx',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA39lS3A3sxMFej20wDfEzA6WXUokiul9E',
    appId: '1:330270178010:ios:37e4d6ddbb7edc675003e3',
    messagingSenderId: '330270178010',
    projectId: 'xorbx-app',
    storageBucket: 'xorbx-app.firebasestorage.app',
    iosBundleId: 'com.example.xorbx',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDicAsaF-Tn50J4ldiCNkkdi7uD0SN11Pk',
    appId: '1:330270178010:web:7de68d9a6126280f5003e3',
    messagingSenderId: '330270178010',
    projectId: 'xorbx-app',
    authDomain: 'xorbx-app.firebaseapp.com',
    storageBucket: 'xorbx-app.firebasestorage.app',
    measurementId: 'G-ZC7EPGBYZ5',
  );
}
